name: alchemist

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.7'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        uses: invertase/github-action-dart-analyzer@v1

      - name: Run tests
        # run: flutter test --no-pub --coverage --test-randomize-ordering-seed=random
        run: flutter test --no-pub --coverage
        continue-on-error: true  # This allows the workflow to continue even if this step fails
      - name: Archive golden tests failures
        uses: actions/upload-artifact@v3
        with:
          name: failures
          path: |
            test/**/failures/*.png
      - uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info

  # pana:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.16.0'
  #         channel: 'stable'
  #         cache: true

  #     - name: Install Dependencies
  #       run: |
  #         flutter packages get
  #         flutter pub global activate pana

  #     - name: Verify Pub Score
  #       run: ./tool/verify_pub_score.sh 130